apiVersion: v2
name: mychart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
  - name: traefik
    version: 28.0.0
    repository: https://traefik.github.io/charts
  - name: argo-cd
    version: 7.4.3
    repository: https://argoproj.github.io/argo-helm
